name: "build"

on:
    pull_request: ~
    push: ~
    workflow_dispatch: ~

jobs:
    run:
        name: "Run action"
        runs-on: "ubuntu-latest"
        steps:
            -   name: "Checkout repository"
                uses: "actions/checkout@v3"
            
            -   name: "Set up PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "latest"
                    coverage: "none"

            -   name: "Test: plain install"
                uses: "./"
